* Chapter 3
  Kyle is woken up by a knock on the door. It's been two weeks since he went there. He decided to wait for the letter
after seeing what happened to the others.

 He puts on some boxers and runs to get it. A man with a short beard hans 
him a white envolope then leaves.

  Kyle sits down and opens the envulope. It's a white card with black embosed letters that say ClubKIty with two black
embosed cat ears in the top corners of the letters. He opens the card and sees congraduations you've been accepted for
a temporary trial membership at ClubKitty. 

  Belwo that is please go to http://www.clubkitty.com/membership put in the username KyleA and password PxY21soAb and 
chooses a membership you'll be charged after your trail is over. 

  He goes to his computer and does it. HE smiles at the sit with uses the same logo as the card except it has a 
black kitten running aroudn the top playing.

  He hesitates at first but remembering Whiskers he goes on and pays for a year's subscription.

  After watching the news on the TV he heads to work. On the drive there all he can think about is that night. Is he
going to see her again. Or was she just to intice him to join. Whill the same guys that got thrown out the night. Or
will he be joining them.

  He sighs befroe going into his job. WHere most of the day it's him thinking about the club. Even when he boss gave
him a bunch of owrk. He noded and started on it. The only thing on his mind is the club
